services:
  postgres:
    image: 'postgres:16-alpine' # Die aktuellste und schlankste Postgres Version
    environment:
      - 'POSTGRES_DB=${LOCAL_DB_NAME}'
      - 'POSTGRES_USER=${LOCAL_DB_USER}'
      - 'POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}'
    ports:
      - '5432:5432'

  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
      - LOCAL_DB_USER=${LOCAL_DB_USER}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}