services:
  postgres:
    image: 'postgres:16-alpine' # Die aktuellste und schlankste Postgres Version
    environment:
      - 'POSTGRES_DB=${LOCAL_DB_NAME}'
      - 'POSTGRES_USER=${LOCAL_DB_USER}'
      - 'POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}'
    ports:
      - '5432:5432'