spring.application.name=simple-meal-planner
spring.devtools.add-properties=false

spring.profiles.default=local
spring.jpa.hibernate.ddl-auto=update

# Recipe API Configuration
recipe.api.key=${RECIPE_API_KEY}
recipe.api.base=https://gustar-io-deutsche-rezepte.p.rapidapi.com
recipe.api.host=gustar-io-deutsche-rezepte.p.rapidapi.com

recipe.api.passwordhash=${RECIPE_API_PWHASH}