spring.datasource.url=jdbc:postgresql://localhost:5432/${LOCAL_DB_NAME}
spring.datasource.username=${LOCAL_DB_USER}
spring.datasource.password=${LOCAL_DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public
spring.jpa.hibernate.ddl-auto=validate

# Wichtig: Backend-Container ist auf Port 8080
# Daher muss beim starten der Spring-Boot-Applikation durch die IDE ein anderen Port gewählt werden
# Port-Konflikt wird dadurch vermieden.
# Wird JavaFX nicht mehr verwendet, so kann diese Einstellung gelöscht werden (Default: Port 8080)
server.port=8081