spring.application.name=simple-meal-planner
spring.devtools.add-properties=false

spring.profiles.default=local
# 'validate': Flyway; zuvor 'update'
spring.jpa.hibernate.ddl-auto=validate

# Spring Boot Port Configuration
# -> Diese Einstellung überschreibt die Standardportnummer 8080, damit die Anwendung auf Port 8081 läuft.
# -> Wichtig, weil der Backend-Container für Flutter auf Port 8080 läuft, und wir möchten Konflikte vermeiden.
# server.port=8080

# Recipe API Configuration
recipe.api.key=${RECIPE_API_KEY}
recipe.api.base=https://gustar-io-deutsche-rezepte.p.rapidapi.com
recipe.api.host=gustar-io-deutsche-rezepte.p.rapidapi.com

recipe.api.passwordhash=${RECIPE_API_PWHASH}