spring.application.name=simple-meal-planner
spring.devtools.add-properties=false

spring.datasource.url=jdbc:postgresql://localhost:5432/${LOCAL_DB_NAME}
spring.datasource.username=${LOCAL_DB_USER}
spring.datasource.password=${LOCAL_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

pantry.file=src/main/resources/pantry.json
recipebook.file=src/main/resources/recipebook.json
mealplans.file=src/main/resources/mealplans.json

temp.file=src/main/resources/test.json



# Recipe API Configuration
recipe.api.key=${RECIPE_API_KEY}
recipe.api.base=https://gustar-io-deutsche-rezepte.p.rapidapi.com/search_api?text=
recipe.crawl.base=https://gustar-io-deutsche-rezepte.p.rapidapi.com/crawl?target_url=
recipe.api.host=gustar-io-deutsche-rezepte.p.rapidapi.com

recipe.api.passwordhash=${RECIPE_API_PWHASH}