pantry.file=pantry.json
recipebook.file=recipebook.json
mealplans.file=mealplans.json

temp.file=test.json

# Recipe API Configuration
recipe.api.key=edc03d7d63msh21057ed778fcb51p11bf96jsn37a8e42de6f0
recipe.api.base=https://gustar-io-deutsche-rezepte.p.rapidapi.com/search_api?text=
recipe.crawl.base=https://gustar-io-deutsche-rezepte.p.rapidapi.com/crawl?target_url=
recipe.api.host=gustar-io-deutsche-rezepte.p.rapidapi.com

recipe.api.passwordhash=d8d12ae3d06730d929efd128d9b99e653175f906f0c51a18d03ed08570824205

