pantry.file=pantry.json
recipebook.file=recipebook.json
mealplans.file=mealplans.json

temp.file=test.json

# Recipe API Configuration
recipe.api.key=edc03d7d63msh21057ed778fcb51p11bf96jsn37a8e42de6f0
